### ISSUE TITLE
我的WeChat：jianlei12

### ISSUE THREAD

**Issue by vhjmlw** [FredZeng/Hexo-Blog#3]
你好，你回复了我在video.js里面提的一个issue，说http-streaming这个插件可以解决播放H265编码格式视频的问题，想咨询下具体的用法，方便的话可以加下微信吗，我的微信：jianlei12

**Comment by FredZeng** [comment]
当时没看清楚是 h265，可以忽略我的回答，看官方的回复。video.js 能播放什么编码格式的视频，主要还是依赖浏览器提供的编解码能力。目前主流浏览器支持的还是 h264。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FredZeng/Hexo-Blog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 中午11:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[FredZeng/Hexo-Blog] 我的WeChat：jianlei12 (#3)





 
你好，你回复了我在video.js里面提的一个issue，说http-streaming这个插件可以解决播放H265编码格式视频的问题，想咨询下具体的用法，方便的话可以加下微信吗，我的微信：jianlei12
